### ISSUE TITLE
pyhsmm on windows

### ISSUE THREAD

**Issue by pawarrick** [mattjj/pyhsmm#27]
Hi,
After a few days of various combinations of python environments and difficulties with the pyhsmm install, I thought I would check in to see if I there was something I could do that would be more successful.  Here's the steps I've taken:

2) Install Anaconda-2.0.1-Windows-x86_64
3) Download pyhsmm
4) Install pyhsmm:
        python setup.py build_ext --inplace
5) Errors during compile of first cpp file: hmm_messages_interface.cpp: 
        "::hypot not defined"
6) From http://bugs.python.org/issue11566:
        add #include cmath earlier than python.h, i.e., at the top of   hmm_messages_interface.cpp
7) "::hypot" error no longer appears, but the next one remains: 
"error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]"

I don't see a quick fix to that one in the searches that I've done.

Below is the full install console output.  You will notice that I am using the gcc that comes with Anaconda (4.7.0). You do suggest using 4.8 and a quick check of using that instead gave the same errors.

Any thoughts would be most appreciated,
Phil

running build_ext
building 'internals.hmm_messages_interface' extension
D:\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Ideps/Eigen3/ -ID:\Anaconda\lib\site-packages\numpy\core\include -ID:\Anaconda\include -ID:\Anaconda\PC -c internals\hmm_messages_interface.cpp -o build\temp.win-amd64-2.7\Release\internals\hmm_messages_interface.o -O3 -w -DNDEBUG -std=c++11 -DHMM_TEMPS_ON_HEAP -DTEMPS_ON_STACK
In file included from D:\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1761:0,
                 from D:\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:17,
                 from D:\Anaconda\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                 from internals\hmm_messages_interface.cpp:351:
D:\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:13:79: note: #pragma message: D:\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
In file included from d:\anaconda\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/complex:46:0,
                 from deps/Eigen3/Eigen/Core:56,
                 from internals\hmm_messages.h:4,
                 from internals\hmm_messages_interface.cpp:359:
d:\anaconda\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/cmath:1096:11: error: '::hypot' has not been declared
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_68sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:10987:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_70sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:11265:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_72sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:11543:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_74sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:11821:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_76sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:12099:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_78sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:12377:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_80sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:12655:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_82sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:12933:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_84sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:13211:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_86sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:13489:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_88sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:13767:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_90sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:14045:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_92sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:14323:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_94sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:14601:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_96sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:14879:865: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_98sample_forwards_log(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:15157:874: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:267:17: error:   initializing argument 7 of 'static void hmmc<FloatType, IntType>::sample_forwards_log(int, int, FloatType_, FloatType_, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_266sample_backwards_normalized(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:44761:645: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:277:17: error:   initializing argument 5 of 'static void hmmc<FloatType, IntType>::sample_backwards_normalized(int, int, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_268sample_backwards_normalized(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:45004:650: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:277:17: error:   initializing argument 5 of 'static void hmmc<FloatType, IntType>::sample_backwards_normalized(int, int, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_270sample_backwards_normalized(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:45247:645: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:277:17: error:   initializing argument 5 of 'static void hmmc<FloatType, IntType>::sample_backwards_normalized(int, int, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_272sample_backwards_normalized(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:45490:650: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:277:17: error:   initializing argument 5 of 'static void hmmc<FloatType, IntType>::sample_backwards_normalized(int, int, FloatType_, FloatType_, IntType_, FloatType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_286viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:50903:602: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_288viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:51099:608: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_290viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:51295:602: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_292viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:51491:608: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_294viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:51687:602: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_296viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:51883:608: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = double; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_298viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:52079:602: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = float; IntType = int]' [-fpermissive]
internals\hmm_messages_interface.cpp: In function 'PyObject\* __pyx_pf_6pyhsmm_9internals_22hmm_messages_interface_300viterbi(PyObject_, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyArrayObject_)':
internals\hmm_messages_interface.cpp:52275:608: error: invalid conversion from '__pyx_t_5numpy_int32_t\* {aka long int_}' to 'int_' [-fpermissive]
In file included from internals\hmm_messages_interface.cpp:359:0:
internals\hmm_messages.h:282:17: error:   initializing argument 6 of 'static void hmmc<FloatType, IntType>::viterbi(int, int, FloatType_, FloatType_, FloatType_, IntType_) [with FloatType = double; IntType = int]' [-fpermissive]
error: command 'D:\Anaconda\Scripts\gcc.bat' failed with exit status 1

**Comment by allista** [comment]
I've just encounterd the same problem with pointer casting and had to change **h(s)mm_messages_interface.pyx** files as you explained here (defining *stateseq* as *int32_t* array and returning it using *np.asarray*) to be able to build and install from git. The installation from PyPI has failed with the same bug.
My environment is:

> Linux 3.13.0-74-generic #118-Ubuntu SMP i686 athlon GNU/Linux
> Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2] on linux2
> Cython (0.23.4)
> numpy (1.10.2)
> scipy (0.16.1)

**Comment by mattjj** [comment]
@allista Thanks for pointing that out. Maybe that diff should be applied to master; can you spell out exactly what you changed (or make a PR)?
