### ISSUE TITLE
travis CI

### ISSUE THREAD

**Issue by mattjj** [mattjj/pyhsmm#36]
Inspired by the recent successful setup.py improvements and pypi integration, it would be great to get pyhsmm and pybasicbayes tests set up with [Travis CI](https://travis-ci.org).

**Comment by yarden** [comment]
Integration with travis CI would be great. This *might* require one last upgrade to ``setup.py`` to force the CI system to run Cython when making a source distribution (``python setup.py sdist``), according to this: http://stackoverflow.com/questions/4505747/how-should-i-structure-a-python-package-that-contains-cython-code

Based on that post, we'd need to override the ``sdist`` class using something like this code (from above link):

```
from distutils.command.sdist import sdist as _sdist
class sdist(_sdist):
    def run(self):
        # Make sure the compiled Cython files in the distribution are up-to-date
        from Cython.Build import cythonize
        cythonize(['cython/mycythonmodule.pyx'])
        _sdist.run(self)
cmdclass['sdist'] = sdist
```

I don't have experience with travis CI so I don't know if that'd be necessary.

**Comment by mattjj** [comment]
Just added Travis integration!
