### ISSUE TITLE
Multimodal emission probabilites?

### ISSUE THREAD

**Issue by mathDR** [mattjj/pyhsmm#44]
Did you ever extend this package to include HDP priors for Gaussian Mixtures for the emission probabilities? I am trying to locate the acceptable probabilities for emission distributions, but can only find Gaussian.

Thanks

**Comment by mattjj** [comment]
The distributions are mostly [in pybasicbayes's distributions.py](https://github.com/mattjj/pybasicbayes/blob/90dc4672bcc9a7d100aa81f4426cda930a3a2f2e/pybasicbayes/distributions.py). To make a mixture that can be plugged into an HMM, you'd also want to use the [MixtureDistribution class](https://github.com/mattjj/pybasicbayes/blob/90dc4672bcc9a7d100aa81f4426cda930a3a2f2e/pybasicbayes/models.py#L390). Something like this:

```
from pybasicbayes.models import MixtureDistribution
from pybasicbayes.distributions import Gaussian

obs_distns = \
    [MixtureDistribution(
        alpha_0=5.,
        components=[Gaussian(**obs_hypparams) for _ in xrange(5)])
    for state in range(Nmax)]
```

By default those MixtureDistributions act like weak limit approximations to Dirichlet Process mixture models. If you want to make an HDP model (including multiple mixture models) you'll have to write the hierarchical prat yourself.

You can make mixtures of any of the distributions in pybasicbayes (and it's pretty easy to add new ones).
