### ISSUE TITLE
Use regular HMM and HSMM

### ISSUE THREAD

**Issue by jmgo** [mattjj/pyhsmm#63]
Hi, 

this not really an issue, I just have a doubt about the capabilities of the package. 

Does the package contains the optimization procedures for the regular HMM and HSMM? I want to know this, in order to be able to compare the results of the regular H(S)MM and HDP-H(S)MM.

Regards, 
jmgo

**Comment by mattjj** [comment]
It depends on what you mean by 'optimization procedures', but EM for both of those models is supported. The class names in models.py should make clear which classes correspond to which models.

**Comment by jmgo** [comment]
Ok, thanks for the answer, that was what I wanted to know.

**Comment by Zhijing1128** [comment]
Hi @mattjj 

can you provide more detailed tutorials of using the regular HSMM? Suppose there's no probability assumption. 

Besides, in the code, I don't quite understand the parameters in the __init__ of HSMMBase. I thought usually we should pass the initial state trans matrix, initial state-observation matrix and initial state probability, and initial duration probability matrix to it. I don't understand why there's an alpha, and what's init_state_concentration?

I appreciate it if you can explain more about it.

**Comment by mathDR** [comment]
@Zhijing1128 There is a paper on it:  http://www.mit.edu/~mattjj/papers/uai2010.pdf

**Comment by mattjj** [comment]
My [thesis](http://people.csail.mit.edu/mattjj/thesis.pdf) has some more info and is a bit more cleaned up, particularly [Ch 2](http://people.csail.mit.edu/mattjj/thesis/ch2.pdf) and [Ch 3](http://people.csail.mit.edu/mattjj/thesis/ch3.pdf).

Unfortunately I can't write more of a tutorial right now, but take a look at the [examples directory](https://github.com/mattjj/pyhsmm/tree/master/examples) if you haven't already.
