### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jmgo** [mattjj/pyhsmm#72]
Hi!

Is it possible to use distributions for duration (HSMM) when using the viterbi method? In my case I just set the HMM model (intial, observational and transitional models) and then use the Viterbi algorithm (see the code below). I do not use any optimization because I am operating in a supervised setting. 

```
hmm = HMM(trans_matrix=trans_matrix,  obs_distns=obs_distns, pi_0 = pi_0)
output_seq = hmm.heldout_viterbi(data) 
```

Best regards,
jmgo

**Comment by mattjj** [comment]
Yes, just create an HSMM instance instead (passing `dur_distns` to the constructor) and the same thing should work. (The Viterbi methods are inherited from the HMM parent classes, which is hard to see with the mixin style the code is written in.) [This method](https://github.com/mattjj/pyhsmm/blob/8afe672398024542a43222dc5def6620dbf97b16/pyhsmm/internals/hsmm_states.py#L344) ultimately gets called, which calls [this HSMM Viterbi function](https://github.com/mattjj/pyhsmm/blob/8afe672398024542a43222dc5def6620dbf97b16/pyhsmm/internals/hsmm_states.py#L1091). It looks like we don't have low-level code for HSMM Viterbi.

**Comment by jmgo** [comment]
Thank you very much for the answer!

Ok, if any error pops out I'll inform you. 

Regards,
jmgo
