### ISSUE TITLE
Use pcolormesh with matplotlib 2.0

### ISSUE THREAD

**Issue by nfoti** [mattjj/pyhsmm#73]
The `pcolorfast` function throws an error when used in `matplotlib` 2.0. However, in `models._plot_stateseq_pcolor` where it is called there is a comment suggesting the use of `pcolormesh`. I have verified that `pcolormesh` does work with `matplotlib` 2.0 so this change should probably be made.

I'm happy to make a PR, but it may just be easier for @mattjj to make the change.

**Comment by mattjj** [comment]
Looks like it was just a drop-in replacement. Does that sound right to you?

**Comment by nfoti** [comment]
Yes, that's all it was.
